### ISSUE TITLE
Pdb::Sym::cast: Invalid type cast.

### ISSUE THREAD

**Issue by liwei1024** [HoShiMin/formatPE#1]
Hello, how do you convert the function?
mod.find(L"NtOpenProcess").cast<Pdb::SymFunc>();
mod.find(L"NtOpenProcess").cast<Pdb::SymFuncArg>();
Both are Pdb::Sym::cast: Invalid type cast.

**Comment by HoShiMin** [comment]
Hm. Really, these functions have the type PublicSymbol, not Function. I'll do support for it.

**Comment by HoShiMin** [comment]
Added support for SymPublicSymbol.
You can't deal with it as with SymFunc in case of stripped symbols (like PDBs for system libraries provided by Microsoft): you can extract an address, name and size only, no more.
You can't even determine what exactly is it - a function, exported constant or something else.
So, if you have private symbols - you can deal with PdbFunc and parse arguments and calling convention, but if you have only public/stripped symbols - use PdbPublicSymbol instead for functions and exported data.
